const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const DEFAULT = 500;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;

module.exports = {
  FORBIDDEN,
  UNAUTHORIZED,
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT,
};
